In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent= ['the glass of milk' ,
'the glass of juice',
'The cup of tea',
'I am a good boy',
'I am a good developer',
'your videos are good']

In [3]:
voc_size= 10000


In [4]:
one_hot_repr= [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[9020, 250, 6277, 4730],
 [9020, 250, 6277, 6640],
 [9020, 7145, 6277, 9229],
 [2347, 1456, 3399, 4090, 2750],
 [2347, 1456, 3399, 4090, 1423],
 [8211, 1014, 6282, 4090]]

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np


In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr , padding='pre', maxlen = sent_length)

In [11]:
print(embedded_docs)

[[   0    0    0    0 9020  250 6277 4730]
 [   0    0    0    0 9020  250 6277 6640]
 [   0    0    0    0 9020 7145 6277 9229]
 [   0    0    0 2347 1456 3399 4090 2750]
 [   0    0    0 2347 1456 3399 4090 1423]
 [   0    0    0    0 8211 1014 6282 4090]]


In [15]:
dim = 10
model = Sequential()
model.add(Embedding(voc_size,dim , input_length = sent_length))
model.compile('adam','mse')

d:\MLwork\.venv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step


array([[[ 0.01538685, -0.01729286,  0.02057156, -0.02628403,
          0.03207112,  0.01982549, -0.04723312,  0.00376092,
          0.02817896,  0.04521059],
        [ 0.01538685, -0.01729286,  0.02057156, -0.02628403,
          0.03207112,  0.01982549, -0.04723312,  0.00376092,
          0.02817896,  0.04521059],
        [ 0.01538685, -0.01729286,  0.02057156, -0.02628403,
          0.03207112,  0.01982549, -0.04723312,  0.00376092,
          0.02817896,  0.04521059],
        [ 0.01538685, -0.01729286,  0.02057156, -0.02628403,
          0.03207112,  0.01982549, -0.04723312,  0.00376092,
          0.02817896,  0.04521059],
        [-0.02612966, -0.04224296,  0.025163  ,  0.0184483 ,
         -0.02680026, -0.01924394, -0.0362919 , -0.00054134,
         -0.02495097,  0.00804299],
        [ 0.01829663,  0.03812846,  0.03849243,  0.04357092,
         -0.00317587, -0.01583302, -0.04542201, -0.02493247,
         -0.0368216 ,  0.0135823 ],
        [-0.04124625,  0.0407066 ,  0.029587  , -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 9020,  250, 6277, 4730])